steps:
  # Cloud Run üzerine doğrudan kaynak koddan (Dockerfile kullanarak) otomatik yayınla
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'yks-takip-sistemi'
      - '--source'
      - '.'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
